// <auto-generated />
namespace Library_system.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class new_AccountTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(new_AccountTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201909141903323_new_AccountTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
